Making sudo calls passwordless. Added API function to backup and restore files and folders
* cloudify
** Added Cloudify API functions to locally backup and restore files and folders
** Added Cloudify API function to apt install package with sudo password read from an env var
** sudo calls don't prompt for password anymore as they take password from an env var
** DEBUG log prints (colorized) file, line and function of debug line

* pkg/dotfiles/init.sh
** BROKEN: incomplete code to make git calls password less

* Oter pkg/*/init.sh
** Replacing direct calls to apt-get install and add-apt-repository by passwordless Cloudify API function

diff --git a/cloudify b/cloudify
--- a/cloudify
+++ b/cloudify
@@ -24,7 +24,7 @@ EOF
 PKG_INIT_FILE_DEFAULT="init.sh"
 PKG_INIT_FILE_TERMUX="termux.init.sh"
 LOCAL_BIN="$HOME"/.local/bin
-LOCAL_TMP=/tmp/cloudify
+export CLOUDIFY_TMP=/tmp/cloudify
 export EDITOR=vim                           # If an editor is needed during install 
 
 # ENVIRONMENT
@@ -34,28 +34,35 @@ export EDITOR=vim                           # If an editor is needed during inst
 # Default assumed platform
 export PKG_PLATFORM="ubuntu"
 
-# CLEANUP
+# DEBUG STATE
+: "${CLOUDIFY_DEBUG:=false}"                           # If CLOUDIFY_DEBUG isn't set, set it to false. 
+export CLOUDIFY_DEBUG                                  # Export it so it's available in subshells
+
+# CLEANUP BEFORE EXIT 
 # Call clean up function before exiting script
 trap cleanup SIGINT SIGTERM ERR EXIT
 cleanup() {
   trap - SIGINT SIGTERM ERR EXIT
   
   # script cleanup here
-  "$CLOUDIFY_DEBUG" || rm -rf "${LOCAL_TMP}"
+#  "$CLOUDIFY_DEBUG" || rm -rf "${CLOUDIFY_TMP}"
 }
 
 
-# DEBUG STATE
-: "${CLOUDIFY_DEBUG:=false}"                           # If CLOUDIFY_DEBUG isn't set, set it to false. 
-export CLOUDIFY_DEBUG                                  # Export it so it's available in subshells
-
+# DEBUG FUNCTIONS
 # Print a DEBUG message
 function PKG_DEBUG() {
-  $CLOUDIFY_DEBUG && msg "${RED}*** DEBUG: $1 ***${RESET}" || true
+  #DEBUG_PROMPT='\033[0;33m+(${BASH_SOURCE}:${BASH_LINENO[0]}):\033[0m ${FUNCNAME[0]:+${FUNCNAME[0]}(): } '
+
+#  echo  "DEBUG: ${ORANGE}+(${BASH_SOURCE}:${BASH_LINENO[0]}):${RESET} ${FUNCNAME[0]:+${FUNCNAME[0]}()}${ORANGE} $1${RESET}"
+
+  $CLOUDIFY_DEBUG && msg "${RED}*** DEBUG *** ${ORANGE}+(${BASH_SOURCE}:${BASH_LINENO[0]}):${PURPLE} ${FUNCNAME[0]:+${FUNCNAME[0]}()}${ORANGE} $1${RESET}" || true
 }
 # Print a DEBUG message after a new line 
 function PKG_DEBUG_LN() {
-  $CLOUDIFY_DEBUG && msg "${RED}\n*** DEBUG: $1 ***${RESET}" || true
+#  $CLOUDIFY_DEBUG && msg "${ORANGE}\n*** DEBUG: $1 ***${RESET}" || true
+  echo
+  PKG_DEBUG $@ 
 }
 
 # GENERAL UTILITIES
@@ -104,32 +111,135 @@ msg() {
   fi
 }
 
+
+
 #############################################################
-############################################# THROWAWAY CODE!
+############################################# JUNK CODE!
 
-function prompt2var() {
-  local prompt="$1"
-  local answervar="$2"
-  msg -n "${GREEN}$1${RESET} "
-  read "$answervar" 
-}
-
-function prompt2pass() {
-  local answervar="$1"
-  # This utility script reads the password in PWORD 
-  local answer=$("$LOCAL_BIN"/askpass_stars.sh)
-  export "$answervar"="$answer"
-}
-
-
-# Throw away code that can be tested w/ 'cloudify test' 
+# Junk code that can be tested w/ 'cloudify test' 
 # Use this to test code before inserting it in cloudify 
 
-function throwawaycode () {
-  echo "No throw away code to test"
+function git() {
+  # backup current .gitconfig
+  git config --global url."https://api@github.com/".insteadOf "https://github.com/"
+  git config --global url."https://ssh@github.com/".insteadOf "ssh://git@github.com/"
+  git config --global url."https://git@github.com/".insteadOf "git@github.com:"
 }
 
-###################################### END OF THROWAWAY CODE!
+
+# Backup files
+pkg_backup() {
+  PKG_DEBUG "Running backup"
+
+  # Do we keep the same name for the target and its target
+  same=false; [[ "${1-}" == "--same" ]] && same=true && shift
+
+  if [[ ! -e ${1-} ]]; then
+    PKG_DEBUG "File or directory ${1-} not found"
+    return 1
+  fi
+  
+  PKG_DEBUG "Testing same flag"
+
+  # Derive a unique file name for the backup by getting the absolute path of the target and replacing by '/' by '__'
+
+  if "$same"; then
+    backup_name=$(basename ${1-}) 
+  else 
+    backup_name=$(dirname ${1-}) && backup_name="$(basename ${1-})${backup_name//\//@}"
+  fi
+  backup_name="${CLOUDIFY_TMP}"/backup/${backup_name}
+
+  PKG_DEBUG "Backing up ${1-} to ${backup_name}"
+
+  [[ -d "${CLOUDIFY_TMP}"/backup ]] || PKG_DEBUG "Creating ${CLOUDIFY_TMP}/backup directory" && mkdir -p "${CLOUDIFY_TMP}"/backup 
+
+  rm -rf  "${backup_name}.bak.5"                         2>/dev/null 
+  mv      "${backup_name}.bak.4" "${backup_name}.bak.5"  2>/dev/null 
+  rm -rf  "${backup_name}.bak.4"                         2>/dev/null 
+  mv      "${backup_name}.bak.3" "${backup_name}.bak.4"  2>/dev/null  
+  rm -rf  "${backup_name}.bak.3"                         2>/dev/null
+  mv      "${backup_name}.bak.2" "${backup_name}.bak.3"  2>/dev/null 
+  rm -rf  "${backup_name}.bak.2"                         2>/dev/null
+  mv      "${backup_name}.bak.1" "${backup_name}.bak.2"  2>/dev/null
+  rm -rf  "${backup_name}.bak.1"                         2>/dev/null
+  mv      "${backup_name}.bak"   "${backup_name}.bak.1"  2>/dev/null
+  rm -rf  "${backup_name}.bak"                           2>/dev/null
+  mv      "${backup_name}"       "${backup_name}.bak"    2>/dev/null
+  rm -rf  "${backup_name}"                               2>/dev/null
+  cp -paf "$1" "${backup_name}"
+}
+
+pkg_restore() {
+  PKG_DEBUG "Running Restore"
+
+  [[ ! -d "${CLOUDIFY_TMP}"/backup ]] && PKG_DEBUG "No backup directory found" && return 1 
+  
+  # Do we keep the same name for the target and its target
+  same=false; [[ "${1-}" == "--same" ]] && same=true && shift
+
+  # Derive a unique file name for the backup by getting the absolute path of the target and replacing by '/' by '__'
+  "$same" && backup_name=${1-} || backup_name=$(dirname $1) && backup_name="$(basename ${1-})${backup_name//\//@}"
+  backup_name="${CLOUDIFY_TMP}"/backup/${backup_name}
+
+  if [[ ! -e "${backup_name-}" ]]; then
+    PKG_DEBUG "File or directory ${1-} has no backup"
+    return 1
+  fi
+
+  PKG_DEBUG "Restoring ${backup_name} to ${1-}"
+
+  trash-put "$1"                                       2>/dev/null 
+  mv     "${backup_name}" "$1"                         2>/dev/null 
+  rm -rf "${backup_name}"                              2>/dev/null 
+  mv     "${backup_name}.bak"  "${backup_name}"        2>/dev/null
+  rm -rf "${backup_name}.bak"                          2>/dev/null 
+  mv     "${backup_name}.bak.1" "${backup_name}.bak"   2>/dev/null
+  rm -rf "${backup_name}.bak.1"                        2>/dev/null 
+  mv     "${backup_name}.bak.2" "${backup_name}.bak.1" 2>/dev/null
+  rm -rf "${backup_name}.bak.2"                        2>/dev/null 
+  mv     "${backup_name}.bak.3" "${backup_name}.bak.2" 2>/dev/null 
+  rm -rf "${backup_name}.bak.3"                        2>/dev/null 
+  mv     "${backup_name}.bak.4" "${backup_name}.bak.3" 2>/dev/null 
+  rm -rf "${backup_name}.bak.4"                        2>/dev/null 
+  mv     "${backup_name}.bak.5" "${backup_name}.bak.4" 2>/dev/null 
+  
+  return 0                             # If we're then everything is ok. Roll back failures are exptected.
+}
+
+
+function junkCode () {
+
+  HOMETRASH="/home/rbc/cloudify/trash/home"
+
+  if ! pkg_backup "$HOMETRASH/$1"; then echo "pkg_backup return an error"; else echo "done!"; fi
+  echo "content of ~"
+  tree -a $HOMETRASH
+  echo "content of backup"
+  tree -a  "$CLOUDIFY_TMP"/backup
+
+  if ! pkg_backup "$HOMETRASH/$1"; then echo "pkg_backup returned an error"; else echo "done!"; fi
+  echo "content of ~"
+  tree -a  $HOMETRASH
+  echo "content of backup"
+  tree -a "$CLOUDIFY_TMP"/backup
+
+  if ! pkg_restore "$HOMETRASH/$1"; then echo "pkg_restore returned an error"; else echo "done!"; fi
+
+  echo "content of ~"
+  tree -a $HOMETRASH
+  echo "content of backup"
+  tree -a "$CLOUDIFY_TMP"/backup
+
+  if ! pkg_restore "$HOMETRASH/$1"; then echo "pkg_restore returned an error"; else echo "done!"; fi
+
+  echo "content of ~"
+  tree -a $HOMETRASH
+  echo "content of backup"
+  tree -a "$CLOUDIFY_TMP"/backup
+}
+
+###################################### END OF JUNK CODE!
 #############################################################
 
 
@@ -196,25 +306,39 @@ function pkg_in_startuprc(){
   done;
 }
 
+
+# Update apt cache
+function pkg_apt_update() {
+  if [[ "${1-}" == "--force"  || -z "$(find /var/cache/apt/pkgcache.bin -mmin -60)" ]]; then
+    sudo -kS apt-get -q update <<< "$CLOUDIFY_HOSTPWD"
+  fi
+}
+
 # Add apt source
 function pkg_apt_repository() {
   for apt_source in "${@}"; do 
     if ! grep -q "^deb .*${apt_source}" /etc/apt/sources.list.d/*; then
-      sudo add-apt-repository "ppa:${apt_source}" -y
+      sudo -kS add-apt-repository "ppa:${apt_source}" -y <<< "$CLOUDIFY_HOSTPWD"
     fi
   done
-  sudo apt-get -q update 
+  pkg_apt_update --force
 }
 
 
 # Install apt package if not already installed
 function pkg_apt_install() {
   for pkg in "${@}"; do 
-   [[ -z "$(find /var/cache/apt/pkgcache.bin -mmin -60)" ]] &&  sudo apt-get -q update
+   pkg_apt_update 
    # =TODO= Parse apt install output to detect error in installation
    if  ! dpkg -l "$pkg" |& grep -q "^ii  $pkg"; then
      PKG_DEBUG_LN "Installing $pkg apt package"
-     sudo apt-get -q install "$pkg"  -y || die "Error installing $pkg" 1 
+     sudo -kS apt-get -q install "$pkg"  -y  <<< "$CLOUDIFY_HOSTPWD"
+     # If apt-get install failed, we stop cloudify
+     # =TODO= Instead of brutally exiting, log the error and continue with next package installations
+     local exitcode=$?
+     if [ $exitcode -ne 0 ]; then
+        die "Error installing $pkg" $exitcode
+     fi
    fi
   done
 }
@@ -250,21 +374,37 @@ function pkg_install_release() {
     
           # Some install archives have an install/setup script. 
           # If that's the case, let it do its thing (A lot of install/setup scripts read the install directory in a prefix variable )
-          [[ -f /tmp/"$cmd"/install ]] && PKG_DEBUG "Running archive setup script" && sudo prefix=/usr/local bash  /tmp/"$cmd"/install && exit 0
-          [[ -f /tmp/"$cmd"/install.sh ]] && PKG_DEBUG "Running archive setup script" && sudo prefix=/usr/local bash  /tmp/"$cmd"/install.sh && exit 0
-          [[ -f /tmp/"$cmd"/setup ]] && PKG_DEBUG "Running archive setup script" && sudo prefix=/usr/local bash  /tmp/"$cmd"/setup && exit 0
-          [[ -f /tmp/"$cmd"/setup.sh ]] && PKG_DEBUG "Running archive setup script" && sudo prefix=/usr/local bash  /tmp/"$cmd"/setup.sh && exit 0
+          [[ -f /tmp/"$cmd"/install ]] && PKG_DEBUG "Running archive setup script" \
+            && sudo -kS prefix=/usr/local bash  /tmp/"$cmd"/install <<< "$CLOUDIFY_HOSTPWD" \
+            && exit 0
+
+          [[ -f /tmp/"$cmd"/install.sh ]] && PKG_DEBUG "Running archive setup script" \
+            && sudo -kS prefix=/usr/local bash  /tmp/"$cmd"/install.sh <<< "$CLOUDIFY_HOSTPWD" \
+            && exit 0
+
+          [[ -f /tmp/"$cmd"/setup ]] && PKG_DEBUG "Running archive setup script" \
+            && sudo -kS prefix=/usr/local bash  /tmp/"$cmd"/setup <<< "$CLOUDIFY_HOSTPWD" \
+            && exit 0
+
+          [[ -f /tmp/"$cmd"/setup.sh ]] && PKG_DEBUG "Running archive setup script" \
+            && sudo -kS prefix=/usr/local bash  /tmp/"$cmd"/setup.sh <<< "$CLOUDIFY_HOSTPWD"   \
+            && exit 0
            
           # Some install archive contain directly the binary
-          [[ -f /tmp/"$cmd"/"$cmd" ]] && PKG_DEBUG "Installing $cmd binary" && sudo install -Dm 755 /tmp/"$cmd"/"$cmd" /usr/local/bin/ && exit 0
+          [[ -f /tmp/"$cmd"/"$cmd" ]] && PKG_DEBUG "Installing $cmd binary" \
+            && sudo -kS install -Dm 755 /tmp/"$cmd"/"$cmd" /usr/local/bin/ <<< "$CLOUDIFY_HOSTPWD"  \
+            && exit 0
 	  
           # The 'install' command doesn't have a recursive option. We use find as a workaround 
           # This will install each file in the archive at corresping path /usr/local
           # Note we're excluding the first level, as this is the place of files, like LICENSE, that shouldn't be installed 
-	        # =TODO= harden this part. We should only install some directories like bin, man, etc.
 	        for release_dir in 'bin' 'share' 'etc' 'doc'; do
               [[ -d /tmp/"$cmd"/"$release_dir" ]] && PKG_DEBUG "Installing /tmp/$cmd/$release_dir to /usr/local/$release_dir"
-              ([[ -d /tmp/"$cmd"/"$release_dir" ]] && cd /tmp/"$cmd"/"$release_dir" && sudo find . -mindepth 1 -type f  -exec install -Dm 755 "{}" "/usr/local/"$release_dir"/{}" \;)
+
+              if [[ -d /tmp/"$cmd"/"$release_dir" ]]; then
+                ( cd /tmp/"$cmd"/"$release_dir" 
+                sudo -kS find . -mindepth 1 -type f  -exec install -Dm 755 "{}" "/usr/local/"$release_dir"/{}" \; <<< "$CLOUDIFY_HOSTPWD" )
+              fi
 	        done
       )
       PKG_DEBUG "Discarding tmp/$cmd/"
@@ -346,7 +486,7 @@ function preconfigure() {
   check_credentials
 
   # Ensure tmp folder exists
-  [[ -d "$LOCAL_TMP" ]] || mkdir -p "$LOCAL_TMP"
+  [[ -d "$CLOUDIFY_TMP" ]] || mkdir -p "$CLOUDIFY_TMP"
 
   # Ensure ~/.local/bin exists and is in the path
   [[ -d "$LOCAL_BIN" ]] || mkdir -p "$LOCAL_BIN"
@@ -426,9 +566,10 @@ function ask_gitlab_credentials(){
 # If not, ask for credentials and generate a script that the user will source to set the environment variables
 function check_credentials () {
   # Check for credentials environment variables 
-  ## Remote sudo user and password, gitlab and github user and password must be set in env variables 
+  ## sudo user and password, gitlab and github user and password must be set in env variables 
   [[ "${1-}" == "-f" || "${1-}" == "--force" ]] && local force_ask_credentials=true || local force_ask_credentials=false
 
+  local new_credentials=false
   if "$force_ask_credentials" || [[ -z "${CLOUDIFY_HOSTUSER-}" || -z "${CLOUDIFY_HOSTPWD-}" ||  -z "${CLOUDIFY_GITHUBUSER-}" || -z "${CLOUDIFY_GITHUBPWD-}" || -z "${CLOUDIFY_GITLABUSER-}" || -z "${CLOUDIFY_GITLABPWD-}" ]]; then
     local new_credentials=true
     msg "${GREEN}Cloudify needs your Host, Github and Gitlab credentials.${RESET}"
@@ -493,7 +634,7 @@ parse_params () {
           elif [[ "${2-}" == "defaults" ]]; then
             pkg_list_defaults
           else
-            shift && pkg_show "$@"
+            shift && pkg_show $@
           fi
           break ;; 
      i  | install | --install)  
@@ -501,7 +642,7 @@ parse_params () {
           if [[ -z "${2-}" || "${2-}" == "defaults" ]]; then
             pkg_install_defaults
           else
-            shift && pkg_install "$@"
+            shift && pkg_install $@
           fi
           break ;; 
      u  | uninstall | --uninstall) 
@@ -509,14 +650,14 @@ parse_params () {
           if [[ -z "${2-}" || "${2-}" == "defaults" ]]; then
             pkg_uninstall_defaults
           else
-            shift && pkg_uninstall "$@"
+            shift && pkg_uninstall $@
           fi
           break ;; 
      c  | credentials | --credentials) 
           check_credentials --force               # Ask all credentials 
           break ;;
      t  | test | --test) 
-          throwawaycode
+          shift && junkCode $@
           break ;;
 #   -p  | --param) # Named parameter
 #         param="${2-}"
