Refactored and hardened cloudify script (which was a mess)

diff --git a/cloudify b/cloudify
--- a/cloudify
+++ b/cloudify
@@ -1,38 +1,113 @@
-# Workstation installation
+#!/usr/bin/env bash
+# Cloudify all-in-one machine and containers managing tool 
 
-# Constantes
-PKG_INIT_FILE="init.sh"
-PKG_INIT_FILE_TERMUX="termux.init.sh"
+# STRICT MODE ERROR HANDLING
+#set -Eeuo pipefail
 
-function printHelp(){
-cat << EOF
-usage: cloudify:                    print help
-       cloudify help:               print help  
-       cloudify ls|list:            list installable packages 
-       cloudify ls|list default:    list default packages 
+# SCRIPT USAGE
+function usage(){
+cat <<'EOF'
+  cloudify [action] [package]
+  examples:
+       cloudify                     print help
+       cloudify help                print help  
+       cloudify ls|list             list installable packages 
+       cloudify ls|list default     list default packages 
        cloudify i <pkg>             install package
        cloudify i default           install default in termux|station.packages
        cloudify u <pkg>             uninstall package
 EOF
 }
 
-# Set Debug state
+# CONSTANTES 
+PKG_INIT_FILE="init.sh"
+PKG_INIT_FILE_TERMUX="termux.init.sh"
+LOCAL_BIN="$HOME"/.local/bin
+LOCAL_TMP=/tmp/cloudify
+export EDITOR=vim                           # If an editor is needed during install 
+
+# ENVIRONMENT
+# Set CLOUDIFY_DIR a defautl value if not already set
+# Export it as it is needed in subshells
+: "${CLOUDIFY_DIR:=$HOME/cloudify}" && export CLOUDIFY_DIR
+# Default assumed platform
+export PKG_PLATFORM="ubuntu"
+
+# CLEANUP
+# Call clean up function before exiting script
+trap cleanup SIGINT SIGTERM ERR EXIT
+cleanup() {
+  trap - SIGINT SIGTERM ERR EXIT
+  
+  # script cleanup here
+  "$CLOUDIFY_DEBUG" || rm -rf "${LOCAL_TMP}"
+}
+
+
+# DEBUG STATE
 : "${CLOUDIFY_DEBUG:=false}"                           # If CLOUDIFY_DEBUG isn't set, set it to false. 
 export CLOUDIFY_DEBUG                                  # Export it so it's available in subshells
 
 # Print a DEBUG message
 function PKG_DEBUG() {
-  $CLOUDIFY_DEBUG && echo -e "*** DEBUG: $1 ***" || true
+  $CLOUDIFY_DEBUG && msg "${RED}*** DEBUG: $1 ***${RESET}" || true
 }
 # Print a DEBUG message after a new line 
 function PKG_DEBUG_LN() {
-  $CLOUDIFY_DEBUG && echo -e "\n*** DEBUG: $1 ***" || true
+  $CLOUDIFY_DEBUG && msg "${RED}\n*** DEBUG: $1 ***${RESET}" || true
 }
+
+# GENERAL UTILITIES
 
 # Utility function to test if a directory is empty
 function emptydir() {
  ls -1qA "$1" | grep -q .
 }
+
+# Die gracefully
+# Usage: `die "This requirement isn't met" 1
+die() {
+  local msg=$1
+  local code=${2-1} # default exit status 1
+  msg "${RED}$msg${RESET}"
+  exit "$code"
+}
+
+# Farewell message when exiting without error
+function printDone() {
+  msg "${GREEN}\n********************************************************************************${RESET}"
+  msg "${GREEN}  Now please Source ~/.bashrc (Or call rcreload is alias is set)${RESET}"
+  msg "${GREEN}********************************************************************************${RESET}"
+  msg "${GREEN}  Station cloudified!${RESET}"
+  msg "${GREEN}********************************************************************************${RESET}"
+}
+
+# Setup colors code for more readable messages
+setup_colors() {
+  # Setup color codes if we have real terminal on stderr unless colors have been disabled
+  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
+    RESET='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
+  else
+    RESET='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
+  fi
+}
+
+# Print messages with colors
+# msg sends its output to stderr (See 12 Factors CLI app principles) and support special color codes
+# msg "This is a ${RED}very important${RESET} message, but not a script output value!"
+msg() {
+  echo >&2 -e "${1-}"
+}
+
+# CLOUDIFY API 
+# THESE FUNCTION CAN BE CALLED FROM PACKAGE MODULES TO INSTALL SOFTWARE
+# Currently Cloudify API is as simple as 2 functions: 'pkg_depends' and 'pkg_in_startuprc' 
+#
+# pkg_depends:           Most used API function. Declares an explicit dependency. Tries to do its best to install dependencies
+# pkg_in_startuprc:      Safely adds to .bashrc (someday to .zshrc) list of single quoted string given as arguments
+# pkg_apt_repository:    Safely adds apt repository in apt repositories list 
+# pkg_apt_install:       Safely install an apt package   
+# pkg_install_release:   Install cloudify package (Run module code if found or calls pkg_apt_install 
 
 # Write lines listed as single-quoted arguments in .bashrc 
 # =todo= Make it compatible with zsh shell
@@ -45,14 +120,14 @@ function pkg_in_startuprc(){
     PKG_DEBUG "Adding '$pkg_startuprc_line'"
 
     pkg_startuprc_line=$(echo "$pkg_startuprc_line" \
-                     | sed 's/\//\\\//g' \
-  	             | sed 's/\*/\\*/g' \
-	             | sed 's/\-/\\-/g' \
-		     | sed 's/\!/\\!/g' \
-		     | sed 's/\=/\\=/g' \
-		     | sed 's/\:/\\:/g' \
-		     | sed 's/\[/\\[/g'  | sed 's/\]/\\]/g' \
-		     | sed 's/\\(/\\(/g' | sed 's/\\)/\\)/g')
+                       | sed 's/\//\\\//g' \
+        	             | sed 's/\*/\\*/g' \
+	                     | sed 's/\-/\\-/g' \
+		                   | sed 's/\!/\\!/g' \
+		                   | sed 's/\=/\\=/g' \
+		                   | sed 's/\:/\\:/g' \
+		                   | sed 's/\[/\\[/g'  | sed 's/\]/\\]/g' \
+		                   | sed 's/\\(/\\(/g' | sed 's/\\)/\\)/g')
 
     pkg_escaped_lines+=( "$pkg_startuprc_line" )
   done;
@@ -109,7 +184,6 @@ function pkg_apt_install() {
 # Install latest release from Github
 # =TODO= Add installation from gitlab
 # =TODO= Add an argument to force a specific release version  
-# =TODO= ADD an argument to specify release to install (defaults to latest).
 #        Use 'https://api.github.com/repos/USER/REPO/releases' to list all releases
 # =TODO= Should this use 'https://github.com/archf/ghi/blob/master/ghi' ?
 function pkg_install_release() {
@@ -174,39 +248,84 @@ function pkg_depends() {
   done
 }
 
-function printDone() {
-  echo -e "\nNow please Source ~/.bashrc\n***"
-  echo -e "Station on orbit!\n***"
+
+# SCRIPT ACTIONS
+function pkg_list_all() {
+  # List all available packages for current platform
+  \ls "$CLOUDIFY_DIR"/pkg
 }
 
-function main() {
-  # Local Configuration variables
-  
-  # To find cloudify/pkg directory path we naively relied on the following line to retrieve the path of the folder containing this script
-  # Since then cloudify, the script, has been extracted from cloudify, the packages repo, into its own project
-  # So we had to hardcode the path to cloudify/pkg (with an environment variable to customize that path)
-  # CLOUDIFY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-  # Set CLOUDIFY_DIR a defautl value if not already set
-  : "${CLOUDIFY_DIR:=$HOME/cloudify}"
-  # The variable is needed in subshells
-  export CLOUDIFY_DIR
-  
+function pkg_list_defaults() {
+  # List default packages for current platform
+  # Default packages are lited in ./*.packages files 
+  ( for pkg in $(< ${packages_file}); do
+      echo ${pkg%%*( )}
+    done ) | column 
+}
+
+function pkg_show() {
+  # Show module code of packages
+  for pkg in "$@"; do
+    msg "${GREEN}${pkg%%*( )} cloudify package code\n${RESET}"
+    if [[ $PKG_TERMUX && -f "$PKG_INIT_FILE_TERMUX" ]]; then
+      msg "${GREEN}>> $CLOUDIFY_DIR/pkg/${pkg%%*( )}/${PKG_INIT_FILE_TERMUX}${RESET}"
+      cat "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE_TERMUX}              # We use bash expansion to trim spaces at the end of the package name
+    else
+      msg "${GREEN}>> $CLOUDIFY_DIR/pkg/${pkg%%*( )}/${PKG_INIT_FILE}${RESET}"
+      cat "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE}                     # We use bash expansion to trim spaces at the end of the package name
+    fi
+  done
+}
+
+function pkg_install_defaults {
+  # Install default packages for current platform 
+  # Default packages are lited in ./*.packages files 
+  for pkg in $(< ${packages_file}); do
+    msg "${GREEN}Installing ${pkg%%*( )} cloudify package${RESET}"
+    if [[ $PKG_TERMUX && -f "$PKG_INIT_FILE_TERMUX" ]]; then
+      source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE_TERMUX}            # We use bash expansion to trim spaces at the end of the package name
+    else
+      source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE}                   # We use bash expansion to trim spaces at the end of the package name
+    fi
+  done
+  printDone
+}
+
+function pkg_install {
+  # Install specific packages 
+  for pkg in "$@"; do
+    msg "${GREEN}Installing ${pkg%%*( )} cloudify package${RESET}"
+    if [[ $PKG_TERMUX && -f "$PKG_INIT_FILE_TERMUX" ]]; then
+      source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE_TERMUX}              # We use bash expansion to trim spaces at the end of the package name
+    else
+      source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE}                     # We use bash expansion to trim spaces at the end of the package name
+    fi
+  done
+  printDone
+}
+
+function pkg_uninstall_defaults {
+  die "Uninstall package features not ready" 1
+}
+function pkg_uninstall {
+  die "Uninstall package features not ready" 1
+}
+
+
+# Initial configurations before applying script actions
+# Ensure tmp folder exist, local bin exist and is in the path 
+# Test platform on which sript is running
+function preconfigure() {
   # Create local tmp folder 
-  LOCAL_TMP="$HOME"/tmp/
   [[ -d "$LOCAL_TMP" ]] || mkdir -p "$LOCAL_TMP"
-  
-  # Make sure vim is the default editor 
-  export EDITOR=vim                           # If an editor is needed during install 
-  
   # Make sure ~/.local/bin exists and is in the path
-  LOCAL_BIN="$HOME"/.local/bin
   [[ -d "$LOCAL_BIN" ]] || mkdir -p "$LOCAL_BIN"
   [[ ":${PATH}:" != *":${LOCAL_BIN}:"* ]] && export PATH="${PATH}:${LOCAL_BIN}"
   
   # Make LOCAL BIN persistent
   # DIRTY HACK! The comment '# CLOUDIFY LOCAL BIN:' is used by cloudify to avoid doublons in .bashrc
   if ! grep -Fq "# CLOUDIFY LOCAL BIN:" $HOME/.bashrc; then 
-    echo -e "\n# CLOUDIFY LOCAL BIN: Cloudify uses a local at ~/.local/bin to install utility scripts" >> "$HOME"/.bashrc
+    echo -e "\n# CLOUDIFY LOCAL BIN: Cloudify may install utility scripts in ~/.local/bin" >> "$HOME"/.bashrc
     echo 'export LOCAL_BIN="$HOME"/.local/bin' >> "$HOME"/.bashrc
     echo '[[ -d "$LOCAL_BIN" ]] || mkdir -p "$LOCAL_BIN"' >> "$HOME"/.bashrc
     echo '[[ ":${PATH}:" != *":${LOCAL_BIN}:"* ]] && export PATH="${PATH}:${LOCAL_BIN}"' >> "$HOME"/.bashrc
@@ -214,54 +333,132 @@ function main() {
   
   # Are we on Android Termux or Linux station?
   if [ ! -z "$(pgrep -f com.termux)" ]; then
-    export PKG_TERMUX=true
+    export PKG_PLATFORM="termux"
     packages_file=${CLOUDIFY_DIR}/termux.packages
   else
     packages_file=${CLOUDIFY_DIR}/station.packages
   fi
-  
-  # Install packages
-  if [[ -z "$1" || "$1" == "help" ]] ; then
-    # Get help 
-    printHelp
-  elif [[ ( "$1" == "ls" || "$1" == "list" ) && "$2" == "default" ]]; then
-    # List default packages for current platform
-    # Default packages are lited in ./*.packages files 
-    ( for pkg in $(< ${packages_file}); do
-        echo ${pkg%%*( )}
-      done ) | column 
-  elif [[ ( "$1" == "ls" || "$1" == "list" ) && ( -z "$2" || "$2" == "all" ) ]]; then
-    # List all available packages for current platform
-    \ls "$CLOUDIFY_DIR"/pkg
-  elif [[ ( "$1" == "i" || "$1" == "install" ) &&  "$2" == "default" ]]; then
-    # Install default packages for current platform 
-    # Default packages are lited in ./*.packages files 
-    for pkg in $(< ${packages_file}); do
-      PKG_DEBUG_LN "Installing ${pkg%%*( )} cloudify package"
-      if [[ $PKG_TERMUX && -f "$PKG_INIT_FILE_TERMUX" ]]; then
-          source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE_TERMUX}            # We use bash expansion to trim spaces at the end of the package name
-      else
-          source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE}                   # We use bash expansion to trim spaces at the end of the package name
-      fi
-    done
-    printDone
-  elif [[ ( "$1" == "i" || "$1" == "install" ) &&  ! -z "$2" ]]; then
-    # Install a specific package
-    shift                                                                          # Begin argument loop at 2nd argument 
-    for pkg in "$@"; do
-      PKG_DEBUG_LN "Installing ${pkg%%*( )} cloudify package"
-      if [[ $PKG_TERMUX && -f "$PKG_INIT_FILE_TERMUX" ]]; then
-        source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE_TERMUX}              # We use bash expansion to trim spaces at the end of the package name
-      else
-        source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE}                     # We use bash expansion to trim spaces at the end of the package name
-      fi
-    done
-    printDone
-  else
-    # Get help 
-    printHelp
-  fi
 }
 
-# Execute script
-main "$@"
+# PARSE SCRIPT PARAMETERS 
+#  cloudify:                    print help
+#  cloudify help:               print help  
+#  cloudify ls|list:            list installable packages 
+#  cloudify ls|list defaults:   list default packages 
+#  cloudify i <pkg>             install package
+#  cloudify i default           install default in termux|station.packages
+#  cloudify u <pkg>             uninstall package
+parse_params () {
+  # Parse parameters 
+  # default options values 
+  action="install"
+  
+  # Initial setup before running script 
+  preconfigure
+  
+  # Read script parameters
+  while :; do
+    case "${1-}" in
+    -h  | --help | help)
+          usage
+          break
+          ;;
+    -v  | --verbose | verbose) set -x ;;
+    -n  | --no-color) NO_COLOR=1 ;;
+    -l  | ls | list | --list)          
+          if [[ -z "${2-}" || "${2-}" == "all" ]]; then
+            pkg_list_all 
+          elif [[ "${2-}" == "defaults" ]]; then
+            pkg_list_defaults
+          else
+            shift && pkg_show "$@"
+          fi
+          break ;; 
+     i  | install | --install)  
+          if [[ -z "${2-}" || "${2-}" == "defaults" ]]; then
+            pkg_install_defaults
+          else
+            shift && pkg_install "$@"
+          fi
+          break ;; 
+     u  | uninstall | --uninstall) 
+          if [[ -z "${2-}" || "${2-}" == "defaults" ]]; then
+            pkg_uninstall_defaults
+          else
+            shift && pkg_uninstall "$@"
+          fi
+          break ;; 
+#   -p  | --param) # Named parameter
+#         param="${2-}"
+#         shift
+#         ;;
+    -?*) die "Error: Unknown option '$1'" 1;;
+    *) break ;;
+    esac
+    shift
+  done
+
+# Check required params and arguments
+#  [[ -z "${param-}" ]] && die "Missing required parameter: param"
+#  [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
+
+  # Apply cloudify actions
+
+  return 0
+}
+
+# EXECUTE SCRIPT!
+parse_params "$@"
+
+
+## ARCHIVED CODE 
+
+## # Unused but we let it around as it may serve
+## PKG_SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
+
+## function main() {
+##   # Install packages
+##   if [[ -z "$1" || "$1" == "help" ]] ; then
+##     # Get help 
+##     usage
+##   elif [[ ( "$1" == "ls" || "$1" == "list" ) && "$2" == "default" ]]; then
+##     # List default packages for current platform
+##     # Default packages are lited in ./*.packages files 
+##     ( for pkg in $(< ${packages_file}); do
+##         echo ${pkg%%*( )}
+##       done ) | column 
+##   elif [[ ( "$1" == "ls" || "$1" == "list" ) && ( -z "$2" || "$2" == "all" ) ]]; then
+##     # List all available packages for current platform
+##     \ls "$CLOUDIFY_DIR"/pkg
+##   elif [[ ( "$1" == "i" || "$1" == "install" ) &&  "$2" == "default" ]]; then
+##     # Install default packages for current platform 
+##     # Default packages are lited in ./*.packages files 
+##     for pkg in $(< ${packages_file}); do
+##       PKG_DEBUG_LN "Installing ${pkg%%*( )} cloudify package"
+##       if [[ $PKG_TERMUX && -f "$PKG_INIT_FILE_TERMUX" ]]; then
+##           source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE_TERMUX}            # We use bash expansion to trim spaces at the end of the package name
+##       else
+##           source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE}                   # We use bash expansion to trim spaces at the end of the package name
+##       fi
+##     done
+##     printDone
+##   elif [[ ( "$1" == "i" || "$1" == "install" ) &&  ! -z "$2" ]]; then
+##     # Install specific packages 
+##     shift                                                                          # Begin argument loop at 2nd argument 
+##     for pkg in "$@"; do
+##       PKG_DEBUG_LN "Installing ${pkg%%*( )} cloudify package"
+##       if [[ $PKG_TERMUX && -f "$PKG_INIT_FILE_TERMUX" ]]; then
+##         source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE_TERMUX}              # We use bash expansion to trim spaces at the end of the package name
+##       else
+##         source "$CLOUDIFY_DIR"/pkg/${pkg%%*( )}/${PKG_INIT_FILE}                     # We use bash expansion to trim spaces at the end of the package name
+##       fi
+##     done
+##     printDone
+##   else
+##     # Get help 
+##     usage
+##   fi
+## }
+
+
+
